# Copyright 2022 pjds
# See LICENSE file for licensing details.
#
options:
  letsencrypt-acme-email:
    default: ""
    description: Email address to register with lets encrypt.
    type: string
  letsencrypt-acme-hostname:
    default: ""
    description: 
    type: string
  https-bind-address:
    default: "0.0.0.0"
    description: HTTPs bind port
    type: string
  https-bind-port:
    default: "443"
    description: HTTPs bind address.
    type: string
  grpc-bind-port:
    default: "50443"
    description: GRPC bind port.
    type: string
  grpc-bind-address:
    default: "0.0.0.0"
    description: GRPC bind address.
    type: string
  stun-bind-port:
    default: "3478"
    description: stun bind port.
    type: string
  stun-bind-address:
    default: "0.0.0.0"
    description: stun bind address.
    type: string
  https-server-url:
    default: "0.0.0.0"
    description: https server URL.
    type: string
